boats/urls.py
from django.urls import path, re_path
from . import views

app_name = 'boats'

urlpatterns = [
    # /boats/
    path('', views.IndexView, name='index'),
    # /boats/owner/id/
    re_path(r'^owner/(?P<user_id_id>[0-9]+)/$', views.owner_profile, name='owner_profile'),
    # /boats/owner/addboat/id/
    re_path(r'^owner/addboat/(?P<user_id_id>[0-9]+)/$', views.add_boat, name='addboat'),
    # /boats/owner/crewcontract/id/
    re_path(r'^owner/crewcontract/(?P<boat_id_id>[0-9]+)/$', views.crew_contract, name='crew_contract'),
    # /boats/owner/boat_info/id/
    re_path(r'^owner/boat_info/(?P<boat_id_id>[0-9]+)/$', views.boat_info, name='boat_info'),
    # /boats/renter/id/
    re_path(r'^renter/(?P<user_id_id>[0-9]+)/$', views.renter_profile, name='renter_profile'),
    # /boats/renter/id/rentcontract/id/
    re_path(r'^renter/(?P<user_id_id>[0-9]+)/rentcontract/(?P<boat_id_id>[0-9]+)/$', views.rent_contract, name='rent_contract'),
    # /boats/register/
    path('register/', views.register, name='register'),
    path('register/owner', views.register_owner, name='register_owner'),
    path('register/renter', views.register_renter, name='register_renter'),
    # /boats/login/
    path('login/', views.user_login, name='login'),
    # /boats/logout/
    path('logout/', views.user_logout, name='logout'),
    # /boats/id/
    re_path(r'^(?P<boat_id_id>[0-9]+)/$', views.boat_detail, name='boat_detail'),
    # /boats/bay/
    path('bay/', views.bays, name='bay'),
    # /boats/bay/id/
    re_path(r'^bay/(?P<pk>[0-9]+)/$', views.BayDetailView.as_view(), name='bay_detail'),
    # /boats/crew/
    path('crew/', views.CrewIndex, name='crew'),
    # /boats/crew/id/
    re_path(r'^crew/(?P<cr_id>[0-9]+)/$', views.CrewDetail, name='crew_detail'),
    # /boats/competitions/
    path('competitions/', views.Competetions, name='Competitions'),
    # /boats/elling/
    path('elling/', views.elling, name='elling'),
    # /boats/elling/id
    re_path(r'^elling/(?P<el_id>[0-9]+)/$', views.elling_detail, name='elling_detail'),
]

lodki/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boats/', include('boats.urls')),
]

boats/forms.py
from django import forms
from .models import OwnerProfileInfo, RenterProfileInfo, User, Boat, RentContract, BoatCrew, RepairContract, Crew
from django.utils import timezone

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']

class OwnerProfileInfoForm(forms.ModelForm):

    class Meta():
        model = OwnerProfileInfo
        fields = ('date_of_birth', 'phone_number', 'avatar')

class RenterProfileInfoForm(forms.ModelForm):

    class Meta():
        model = RenterProfileInfo
        fields = ('date_of_birth', 'phone_number', 'avatar')

class BoatForm(forms.ModelForm):
    #owner_id = forms.IntegerField(required=False, widget=forms.HiddenInput())
    type = forms.ChoiceField(widget=forms.Select(), choices=([('Go-Fast Boat', 'Go-Fast Boat'),
                                                              ('Luxury Yacht', 'Luxury Yacht'),
                                                              ('Cabin cruiser', 'Cabin cruiser'),
                                                              ('Yacht', 'Yacht'), ]))
    date_of_registration = forms.DateField(widget=forms.HiddenInput(), required=False,
                                     initial=timezone.localtime(timezone.now()).date())
    class Meta:
        model = Boat
        fields = ['name', 'type', 'licence_plate', 'price', 'date_of_registration', 'boat_photo', 'bay_id', 'owner_id']

class RentForm(forms.ModelForm):
    #renter = forms.IntegerField(required=False, widget=forms.HiddenInput())
    #boat = forms.IntegerField(required=False, widget=forms.HiddenInput())
    #total_price = forms.IntegerField(required=False, widget=forms.HiddenInput())

    class Meta:
        model = RentContract
        fields = ['date_begin', 'date_end', 'renter', 'boat', 'total_price']

class CrewContractForm(forms.ModelForm):
    post = forms.ChoiceField(widget=forms.Select(), choices=([('Sailor', 'Sailor'),
                                                                  ('Lieutenant', 'Lieutenant'),
                                                                  ('Midshipman', 'Midshipman'),
                                                                  ('Navigator', 'Navigator'),
                                                                  ('Captain', 'Captain'), ]))
    date_take_post = forms.DateField(widget=forms.HiddenInput(), required=False, initial=timezone.localtime(timezone.now()).date())
    class Meta:
        model = BoatCrew
        fields = ['crew', 'boat', 'post', 'salary', 'date_take_post']

    def __init__(self, *args, **kwargs):
        super(CrewContractForm, self).__init__(*args, **kwargs)
        self.fields["crew"].queryset = Crew.objects.filter(recruited=False)

class RepairContractForm(forms.ModelForm):
    date_end = forms.DateField(widget=forms.HiddenInput(), required=False)
    class Meta:
        model = RepairContract
        fields = ['elling', 'boat', 'date_begin', 'date_end', 'repair_price', 'repair_cause']

    def __init__(self, u_id, *args, **kwargs):
        super(RepairContractForm, self).__init__(*args, **kwargs)
        self.fields["boat"].queryset = Boat.objects.filter(owner_id=u_id)

boats/views.py
from django.views import generic
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import Group
from .models import Boat, Bay, Competitions, OwnerProfileInfo, RenterProfileInfo, RentContract, Crew, BoatCrew, RepairContract, Elling, PriceList, privilege_m
from .forms import UserForm, OwnerProfileInfoForm, RenterProfileInfoForm, BoatForm, RentForm, CrewContractForm, RepairContractForm
from django.utils import timezone
import datetime
from datetime import timedelta
from django.core.exceptions import ValidationError

def IndexView(request):
    if request.method == 'GET':
        if 'by_price' in request.GET and request.GET['by_price']:
            boats = Boat.objects.all().order_by('price')
        elif 'by_repair' in request.GET and request.GET['by_repair']:
            boats = Boat.objects.raw('SELECT Distinct b.id, b.name, b.type, b.price, b.boat_photo FROM boats_boat AS b INNER JOIN boats_repaircontract r ON b.id != r.boat_id;')
        elif 'by_popular' in request.GET and request.GET['by_popular']:
            boats = Boat.objects.raw(
                'SELECT b.id, b.name, b.type, b.price, b.boat_photo, count(r.boat_id) as count FROM boats_boat AS b INNER JOIN boats_rentcontract r ON b.id = r.boat_id group by b.id, b.name, b.type, b.price, b.boat_photo order by count desc;')
        elif 'by_names' in request.GET and request.GET['by_names']:
            boats = Boat.objects.all().order_by('name')
        elif 'by_type' in request.GET and request.GET['by_type']:
            boats = Boat.objects.all().order_by('type')
        elif 'by_price_desc' in request.GET and request.GET['by_price_desc']:
            boats = Boat.objects.all().order_by('-price')
        elif 'by_price_low' in request.GET and request.GET['by_price_low'] and 'by_price_top' in request.GET and request.GET['by_price_top']:
            boats = Boat.objects.all().filter(price__gte=request.GET['by_price_low'], price__lte=request.GET['by_price_top']).order_by('price')
        else:
            boats = Boat.objects.all()
        redirect('boats/index.html')
        context = {'all_boats': boats, }
        return render(request, 'boats/index.html', context)
    else:
        boats = Boat.objects.all()
        context = {'all_boats': boats, }
        return render(request, 'boats/index.html', context)

def boat_detail(request,boat_id_id):
    boat = get_object_or_404(Boat, pk=boat_id_id)
    bay = Bay.objects.get(pk=boat.bay_id_id)
    owner = OwnerProfileInfo.objects.get(pk=boat.owner_id_id)
    contracts = RentContract.objects.filter(boat_id=boat_id_id)
    repairs = RepairContract.objects.filter(boat_id=boat_id_id)
    crews = Crew.objects.all()
    cap = BoatCrew.objects.filter(boat_id=boat_id_id, post='Captain')
    boat_crews = BoatCrew.objects.filter(boat_id=boat_id_id)
    if request.method == "POST":
        if 'new_salary' in request.POST and request.POST['new_salary']:
            BoatCrew.objects.filter(crew_id=request.POST['crew_id_id']).update(salary=request.POST['new_salary'])
        if 'new_post' in request.POST and request.POST['new_post']:
            BoatCrew.objects.filter(crew_id=request.POST['crew_id_id']).update(post=request.POST['new_post'])
        if 'crew_id' in request.POST and request.POST['crew_id']:
            BoatCrew.objects.get(crew=request.POST['crew_id']).delete()
            Crew.objects.filter(pk=request.POST['crew_id']).update(recruited=False)
    context = {'boat': boat, 'bay': bay, 'owner': owner, 'contracts': contracts, 'boat_crews': boat_crews, 'crews': crews, 'repairs': repairs, 'cap': cap,}
    return render(request, 'boats/detail.html', context)

class BayDetailView(generic.DetailView):
    model = Bay
    template_name = 'boats/bay_detail.html'

def Competetions(request):
    comp = Competitions.objects.all()
    boat = Boat.objects.all()
    context = {'competitions': comp, 'boats': boat, }
    return render(request, 'boats/competitions.html', context)

def bays(request):
    bays = Bay.objects.all()
    return render(request, 'boats/bays.html', {'bays': bays, })

def elling(request):
    ell = Elling.objects.all()
    context = {'elling': ell, }
    return render(request, 'boats/elling.html', context)

def elling_detail(request, el_id):
    ell = Elling.objects.get(pk=el_id)
    prices = PriceList.objects.all()
    deal = False
    if request.method == "POST":
        repair_form = RepairContractForm(data=request.POST, u_id=request.user.id)
        if repair_form.is_valid():
            repair = repair_form.save()
            if request.user.id == repair.boat.owner_id_id:
                caus = PriceList.objects.get(cause=repair.repair_cause)
                repair.elling = ell
                repair.date_end = repair.date_begin + timedelta(days=caus.days)
                repair.repair_price = caus.price
                repair.save()
                deal = True
            else:
                raise ValidationError('This is not your boat')
        else:
            print(repair_form.errors)
    else:
        repair_form = RepairContractForm(initial={'elling': ell, 'date_end': datetime.date.today(),}, u_id=request.user.id)

    context = { 'repair_form': repair_form, 'deal': deal, 'elling': ell, 'prices': prices,}
    return render(request, 'boats/elling_detail.html', context)

def CrewIndex(request):
    crews = Crew.objects.all()
    context = {'crews': crews,}
    return render(request, 'boats/crew.html', context)

def CrewDetail(request, cr_id):
    crew = Crew.objects.get(pk=cr_id)
    contracts = BoatCrew.objects.filter(crew_id=cr_id)
    boats = Boat.objects.all()
    context = {'crew': crew, 'contracts': contracts, 'boats': boats,}
    return render(request, 'boats/crew_profile.html', context)

@login_required
def rent_contract(request, user_id_id, boat_id_id):
    rented = False
    renter_id = RenterProfileInfo.objects.get(pk=user_id_id)
    priv = privilege_m.objects.filter(id=request.user.id, role_name='RenterUser')
    boat_id = Boat.objects.get(pk=boat_id_id)
    hacker = False
    if request.method == "POST":
        if priv:
            rent_form = RentForm(data=request.POST)
            if rent_form.is_valid():
                rent = rent_form.save()
                total = rent.date_end - rent.date_begin
                rent.total_price = total.days * boat_id.price
                rent.renter = renter_id
                rent.boat = boat_id
                rent.save()
                rented = True
            else:
                print(rent_form.errors)
        else:
            hacker = True
            rent_form = BoatForm(initial={'boat': boat_id, 'renter': renter_id})
    else:
        rent_form = RentForm(initial={'boat': boat_id, 'renter': renter_id})
    return render(request, 'boats/rent_contract.html', {'rent_form': rent_form, 'renter': renter_id, 'rented': rented, 'hacker': hacker})

@login_required
def add_boat(request, user_id_id):
    if request.user.is_owner:
        added = False
        owner = OwnerProfileInfo.objects.get(pk=user_id_id)
        priv = privilege_m.objects.filter(id=request.user.id, role_name='OwnerUser')
        hacker = False
        if request.method == "POST":
            if priv:
                boat_form = BoatForm(data=request.POST)
                if boat_form.is_valid():
                    boat = boat_form.save()
                    boat.owner_id = owner
                    if boat.type == 'Yacht':
                        boat.bay_id = Bay.objects.get(pk=2)
                    elif boat.type == 'Go-Fast Boat' or boat.type == 'Cabin cruiser':
                        boat.bay_id = Bay.objects.get(pk=1)
                    else:
                        boat.bay_id = Bay.objects.get(pk=3)
                    boat.date_of_registration = timezone.localtime(timezone.now()).date()
                    boat.save()
                    added = True
                else:
                    print(boat_form.errors, boat_form.errors)
            else:
                hacker = True
                boat_form = BoatForm(initial={'owner_id': owner})
        else:
            boat_form = BoatForm(initial={'owner_id': owner})

        return render(request, 'boats/add_boat.html', {'boat_form': boat_form, 'owner': owner, 'added': added, 'hacker': hacker})
    else:
        return render(request, 'boats/add_boat.html',{'wrong': 'Something goes wrong!'})
@login_required
def boat_info(request, boat_id_id):
    if request.method == 'POST':
        if 'new_price' in request.POST and request.POST['new_price']:
            Boat.objects.filter(pk=boat_id_id, owner_id=request.user.id).update(price=request.POST['new_price'])
    boat = Boat.objects.get(id=boat_id_id)
    info = Boat.objects.raw('SELECT * FROM maintance_month(%s)' % boat_id_id)
    crews = BoatCrew.objects.filter(boat_id=boat_id_id).values('date_take_post', 'salary')
    context = {'boat': boat, 'crews': crews, 'infos': info}
    return render(request, 'boats/boat_info.html', context)

@login_required
def crew_contract(request, boat_id_id):
    recruited = False
    boat = Boat.objects.get(pk=boat_id_id)
    priv = privilege_m.objects.filter(id=request.user.id, role_name='OwnerUser')
    hacker = False
    if request.method == "POST":
        if priv:
            cr_contr_form = CrewContractForm(data=request.POST)
            if cr_contr_form.is_valid():
                cr_cntr = cr_contr_form.save()
                cr_cntr.boat = boat
                cr_cntr.save()
                recruited = True
            else:
                print(cr_contr_form.errors, cr_contr_form.errors)
        else:
            hacker = True
            cr_contr_form = BoatForm(initial={'boat': boat})
    else:
        cr_contr_form = CrewContractForm(initial={'boat': boat})

boats/templates/boats/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% load staticfiles %}
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <style>
   A {
    color: black;
   }
   A:visited {
    color: black;
   }
   A:active {
    color: black;
   }
   body {
    background: #F0F8FF;
   }
   .navbar-brand{
    font-family: 'Satisfy', cursive;
}
</style>
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark box-shadow ">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#nav-content" aria-controls="nav-content" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <!-- Brand -->
    <a class="navbar-brand notactive" href="{% url 'boats:index' %}">Yacht club</a>

    <div id="nav-content" class="navbar-collapse collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'boats:index' %}">Yachts</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'boats:crew' %}">Crew's</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'boats:elling' %}">Elling's</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Dropdown
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'boats:Competitions' %}">Competitions</a>
                        <a class="dropdown-item" href="{% url 'boats:bay' %}">Bays</a>
                    </div>
                </li>
                {% if user.is_authenticated %}
                    {% if user.is_owner %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'boats:owner_profile' user.id %}">Logged in as <strong>{{ user.username }} </strong></a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'boats:renter_profile' user.id %}">Logged in as <strong>{{ user.username }} </strong></a>
                        </li>
                    {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'boats:logout' %}">Log out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'boats:register' %}">Register</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'boats:login' %}">Log in</a>
                </li>
                {% endif %}
            </ul>
        </div>

</nav>
{% block body %}
{% endblock %}
</body>
</html>

boats/templates/boats/detail.html
{% extends 'boats/base.html' %}
{% block title %}Yacht profile{% endblock %}
{% block body %}
<script type="text/javascript" src="/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.easing-1.4.pack.js"></script>
<script type="text/javascript" src="/fancybox/jquery.mousewheel-3.0.4.pack.js"></script>
<link rel="stylesheet" href="/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    border: 1px solid #dddddd;
    text-align: left;
    padding: 8px;
}

tr:nth-child(even) {
    background-color: #dddddd;
}
    #container {
  width: 100%;
  height: 300px;
  padding: 2%;
}
</style>
<div class="container">
    <div class="row my-2">
        <div class="col-lg-7 order-lg-2">
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a href="" data-target="#about" data-toggle="tab" class="nav-link active">About</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#contracts" data-toggle="tab" class="nav-link">Contracts</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#crew" data-toggle="tab" class="nav-link">Crew</a>
                </li>
                <li class="nav-item">
                    <a href="" data-target="#repair" data-toggle="tab" class="nav-link">Repairs</a>
                </li>
            </ul>
            <div class="tab-content py-4">
                <div class="tab-pane active" id="about">
                    <h5 class="mb-3">{{ boat.name }}</h5>
                    <div class="row">
                        <div class="col-md-6">
                            <p><a class="link" href="{% url 'boats:owner_profile' owner.user_id %}">Owner: {{ owner.user.first_name }} {{ owner.user.last_name }}</a></p>
                            <p>Type: {{ boat.type }}</p>
                            <p><a href="{% url 'boats:bay_detail' bay.id %}">Bay address: {{ bay.address }}</a></p>
                            <p>Licence plate: {{ boat.licence_plate }}</p>
                            <p>Price (per day): {{ boat.price }} $</p>
                            <p>Date of registration: {{ boat.date_of_registration }}</p>
                        </div>
                    </div>
                    <!--/row-->
                </div>

                <div class="tab-pane" id="contracts">
                    {% if contracts %}
                    <div class="jumbotron">
                        <div class="row">
                            <div class="col-md-16">
                                <table border="1px">
                                    <tr>
                                        <th>Contract id</th>
                                        <th style="text-align:center;">Contract cost</th>
                                        <th style="text-align:center;">Terms of contract</th>
                                        <th style="text-align:center;">Renter profile</th>
                                    </tr>
                                    {% for contract in contracts %}
                                    <tr>
                                        <td> {{ contract.id }} </td>
                                        <td style="text-align:center;"> {{ contract.total_price }} $ </td>
                                        <td style="text-align:center;">{{ contract.date_begin }} - {{ contract.date_end }}</td>
                                        <td style="text-align:center;"><a href="{% url 'boats:renter_profile' contract.renter_id %}" class="btn btn-outline-secondary" role="button">Renter profile</a></td>
                                      </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% else %}
                        <h3>No contracts</h3>
                    {% endif %}
                </div>
                <div class="tab-pane" id="crew">
                    {% if owner.user_id == user.id %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <a href="{% url 'boats:crew_contract' boat.id %}"><button type="submit" class="btn btn-outline-secondary">Add crew</button></a>
                            </div>
                        </div>
                    {% endif %}
                    {% if boat_crews %}
                    {% for b_c in boat_crews %}
                    <div class="jumbotron">
                        {% for crew in crews %}
                        {% if b_c.crew_id == crew.id %}
                        <div class="row">
                            <div class="col-sm-4 col-md-4">
                                <div class="thumbnail">
                                    <img style="padding-right:8px;" width="100%" height="100%" src="{{ crew.avatar }}">
                                    <h3>{{ crew.full_name }}</h3>
                                    <p>Experience: {{ crew.experience }} years</p>
                                    <p><a href="{% url 'boats:crew_detail' crew.id %}" class="btn btn-outline-secondary" role="button">Details</a></p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-16">
                                    <p>About</p>
                                    <p>Post: {{ b_c.post }}</p>
                                    <p>Salary: {{ b_c.salary }} $</p>
                                    <p>Date of take the post: {{ b_c.date_take_post }}</p>
                                    {% if owner.user_id == user.id %}
                                    <form action="" method="POST">
                                        {% csrf_token %}
                                        <details>
                                            <summary>Edit</summary>
                                            <div class="col-md-7">
                                                <input id="crew_id_id" type="text" name="crew_id_id" value="{{ crew.id }}" hidden>
                                                New post(required):
                                                <select name="new_post">
                                                    <option value="Sailor">Sailor</option>
                                                    <option value="Lieutenant">Lieutenant</option>
                                                    <option value="Midshipman">Midshipman</option>
                                                    <option value="Navigator">Navigator</option>
                                                    {% if not cap %}
                                                    <option value="Captain">Captain</option>
                                                    {% endif %}
                                                </select>
                                                <p>Enter new salary:</p>
                                                <input size="10%" class="form" type="text" name="new_salary">
                                                <input type="submit" value="Confirm">
                                                </div>
                                        </details>
                                    </form>
                                    {% endif %}
                                </div>
                            </div>
                            {% if owner.user_id == user.id %}
                            <form class="form-horizontal" name="form1" role="form" action="" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input id="crew_id" type="text" name="crew_id" value="{{ crew.id }}" hidden>
                                <input value="Dismiss" type="submit" onclick="return confirm('Are you really want dismiss this crew member?')">
                            </form>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                    {% endfor %}
                    {% else %}
                        <h3>No crew</h3>
                    {% endif %}
                </div>

            <div class="tab-pane" id="repair">
                    {% if owner.user_id == user.id %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <a href="{% url 'boats:elling' %}"><button type="submit" class="btn btn-outline-secondary">New repair</button></a>
                            </div>
                        </div>
                    {% endif %}
                    {% if repairs %}
                    <div class="jumbotron">
                        <div class="row">
                            <div class="col-md-16">
                                <table border="1px">
                                    <tr>
                                        <th>Cause of repair</th>
                                        <th style="text-align:center;">Terms of repair</th>
                                        <th style="text-align:center;">Repair cost</th>
                                    </tr>
                                    {% for repair in repairs %}
                                    <tr>
                                        <td> {{ repair.repair_cause_id }} </td>
                                        <td style="text-align:center;"> {{ repair.date_begin }} - {{ repair.date_end }}</td>
                                        <td style="text-align:center;">{{ repair.repair_price }} $</td>
                                      </tr>
                                    {% endfor %}
                                </table>
                            </div>
                        </div>
                    </div>
                    {% else %}
                        <h3>No repairs</h3>
                    {% endif %}
                </div>
            </div>
        </div>
        <div class="col-lg-5 order-lg-1 text-center">
            <a class="iframe" href="{{ boat.boat_photo }}"><img src="{{ boat.boat_photo }}" class="mx-auto img-fluid img-circle d-block" alt="avatar"></a>
            {% if user.is_renter %}
            <label class="custom-file">
                <a href="{% url 'boats:rent_contract' user.id boat.id  %}">
                <input class="custom-file-input">
                    <button style="width:100%;" type="submit" class="btn btn-outline-secondary">Rent it</button>
                </a>
            </label>
        {% endif %}
        </div>

    </div>
</div>
{% endblock %}

boats/templates/boats/form_template1.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" >{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

boats/templates/boats/registration_form.html
{% extends 'boats/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<br>
<div class="container-fluid">
    <div class="row" >
        <div align="center" class="col-sm-1 col-md-12">
            <div class="panel panel-default">
                <a class="nav-link" href="{% url 'boats:register_renter' %}"><input class="btn btn-outline-secondary" type="submit" name="" value="Register as renter"></a>
                <a class="nav-link" href="{% url 'boats:register_owner' %}"><input class="btn btn-outline-secondary" type="submit" name="" value="Register as owner"></a>
            </div>
        </div>
    </div>

</div>

{% endblock %}